package com.fastkeys1;
import android.graphics.*; import android.inputmethodservice.InputMethodService; import android.os.Handler; import android.view.*; import android.view.inputmethod.InputConnection;
public class FastKeysKeyboardView extends View {
 private final FastKeysInputMethodService s; private final Paint p=new Paint(3); private final Handler h=new Handler(); private float gap=1,kH; private boolean caps; private Runnable rep;
 private final int KEY=Color.rgb(250,249,244),BG=Color.rgb(239,238,232),BLUE=Color.rgb(20,112,235),BLACK=Color.rgb(25,29,34),GREEN=Color.rgb(45,205,55);
 public FastKeysKeyboardView(FastKeysInputMethodService x){super(x);s=x;setBackgroundColor(BG);}
 protected void onDraw(Canvas c){super.onDraw(c);float W=getWidth(),H=getHeight();kH=(H-gap*7)/6f; row(c,0,new String[]{"⌃","Copy All","Copy Screen","Paste","Cut","Undo","Redo","100\nHistory","⌄"},new float[]{.55f,1.55f,1.55f,1.1f,1.1f,1,1,1.25f,.55f},BLACK,false); row(c,1,new String[]{"⌃","!\n۱","@\n۲","#\n۳","$\n۴","%\n۵","^\n۶","&\n۷","*\n۸","(\n۹",")\n۰","-\n_","=\n+","⌫"},new float[]{.55f,1,1,1,1,1,1,1,1,1,1,1,1,1.45f},BLACK,true); row(c,2,new String[]{"🔒 Caps","ض","ص","ث","ق","ف","غ","ع","ه","خ","ج","{\n[","}\n]","|\n\\"},new float[]{1.45f,1,1,1,1,1,1,1,1,1,1,.75f,.75f,.75f},BLUE,false); arrows(c,3); row(c,4,new String[]{"،","ژ","ذ","ز","گ","چ","پ","ب","ن","م","،","/\n؟"},new float[]{1,1,1,1,1,1,1,1,1,1,1,1},BLUE,false); row(c,5,new String[]{"!#@","◎","☺","Space","←","→","↑","↓"},new float[]{1,1,1,4,1.4f,1.4f,1.2f,1.2f},BLACK,false); if(caps){p.setColor(GREEN);c.drawCircle(20,kH*2+gap*2+16,6,p);}}
 private void box(Canvas c,float l,float t,float r,float b){p.setStyle(Paint.Style.FILL);p.setColor(KEY);c.drawRoundRect(l,t,r,b,5,5,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1);p.setColor(Color.LTGRAY);c.drawRoundRect(l,t,r,b,5,5,p);p.setStyle(Paint.Style.FILL);}
 private void txt(Canvas c,String a,float x,float y,float sz,int col){p.setTypeface(Typeface.create("sans",Typeface.NORMAL));p.setTextSize(sz);p.setColor(col);p.setTextAlign(Paint.Align.CENTER);c.drawText(a,x,y-(p.ascent()+p.descent())/2,p);}
 private void row(Canvas c,int n,String[] a,float[] wt,int col,boolean square){float W=getWidth(),y=gap+n*(kH+gap),tot=0;for(float q:wt)tot+=q;float unit=(W-gap*(a.length+1))/tot,x=gap;for(int i=0;i<a.length;i++){float cw=unit*wt[i];box(c,x,y,x+cw,y+kH);String[] z=a[i].split("\\n",-1);if(z.length==1)txt(c,z[0],x+cw/2,y+kH/2,Math.min(22,kH*.42f),col);else{txt(c,z[0],x+cw/2,y+kH*.33f,Math.min(20,kH*.3f),col);txt(c,z[1],x+cw/2,y+kH*.68f,Math.min(20,kH*.3f),col);}x+=cw+gap;}}
 private void arrows(Canvas c,int n){float y=gap+n*(kH+gap);box(c,0,y,150,y+kH);txt(c,"↑",75,y+kH/2,36,BLACK);box(c,0,y+kH+gap,150,y+2*kH+gap);txt(c,"↓",75,y+1.5f*kH+gap,36,BLACK);}
 public boolean onTouchEvent(MotionEvent e){if(e.getAction()==MotionEvent.ACTION_DOWN){touch(e.getX(),e.getY());return true;}if(e.getAction()==MotionEvent.ACTION_UP||e.getAction()==MotionEvent.ACTION_CANCEL){if(rep!=null)h.removeCallbacks(rep);rep=null;return true;}return true;}
 private void touch(float x,float y){int r=(int)((y-gap)/(kH+gap));float W=getWidth();if(r==0)return;if(r==1&&x>W-W*.12){startBack();return;}if(r==2&&x<160){caps=!caps;invalidate();return;}if(r==3){if(x<160){s.move(y<gap+3.9f*kH?KeyEvent.KEYCODE_DPAD_UP:KeyEvent.KEYCODE_DPAD_DOWN);return;}if(x>W-160){s.enter();return;}}if(r==4){String[] a={"،","ژ","ذ","ز","گ","چ","پ","ب","ن","م","،","؟"};s.type(a[Math.min(11,(int)(x/(W/12f)))]);return;}if(r==5){int i=Math.min(7,(int)(x/(W/8f)));if(i==0)s.type("!#@");else if(i==1)s.switchInputMethod(null);else if(i==2)s.type("🙂");else if(i==3)s.type(" ");else if(i==4)s.move(KeyEvent.KEYCODE_DPAD_LEFT);else if(i==5)s.move(KeyEvent.KEYCODE_DPAD_RIGHT);else if(i==6)s.move(KeyEvent.KEYCODE_DPAD_UP);else s.move(KeyEvent.KEYCODE_DPAD_DOWN);}}
 private void startBack(){s.backspace();if(rep!=null)h.removeCallbacks(rep);rep=()->{s.backspace();h.postDelayed(rep,55);};h.postDelayed(rep,350);}
}
